# General configuration
bot_name: "Crypto Trading Bot"
trading_pairs:
  - BTCUSD
  - ETHUSD
  - XRPUSD
  - ADAUSD
  - SOLUSD

# url configuration
api:
  rest_api_url: https://api.kraken.com/0
  ws_api_url: wss://ws.kraken.com