# General configuration
bot_name: "Crypto Trading Bot"

api:
  rest_api_url: https://api.kraken.com/0
  ws_api_url: wss://ws.kraken.com

# Data paths
data_paths:
  historical_data: "data/raw/Kraken_OHLCVT.zip"
  output_path: "data/results"

# Logging configuration
logging:
  config_path: "config/logging_config.yaml"
  log_to_console: false

# Backtest configuration
backtest_config:
  initial_cash: 10000
  max_allocation_pct: 0.25
  commission_pct: 0.001
  slippage_pct: 0.001
  n_jobs: 5

# Strategy parameter ranges for optimization - had to turn optimize off. multithreading causing issues
strategy_params:
  breakout:
    lookback: [12, 18, 30]
    # buffer: [0.001, 0.002, 0.003]
    stop_loss_factor: [0.9, 2.0, 5.5]
    take_profit_factor: [3.0, 6.5, 12.0]
    # volume_multiplier: [0.1, 0.15, 0.2]
    position_size_pct: [0.15, 0.25, 0.4]
  
  mean_reversion:
    base_lookback: [10, 15, 20, 25, 30]
    std_dev_threshold: [1.5, 2.0, 2.5]
    rsi_lookback: [10, 14, 20]
    stop_loss_factor: [1.5, 2.0, 2.5]
    take_profit_factor: [2.5, 3.0, 3.5]
    volume_threshold: [1.2, 1.5, 1.8]
    position_size_pct: [0.15, 0.25, 0.33]

# backtest configurations (kraken historical data files used)
test_configs:
  - file: "XRPUSD_5.csv"
    strategy: "breakout"
    optimize: true
    plot: true
    
  # - file: "ADAUSD_5.csv"
  #   strategy: "mean_reversion"
  #   optimize: false
  #   plot: true
    
  # - file: "ETHGBP_30.csv"
  #   strategy: "breakout"
  #   optimize: false 
  #   plot: false