# General configuration
bot_name: "Crypto Trading Bot"

# Data paths
data_paths:
  historical_data: "data/raw/Kraken_OHLCVT.zip"
  output_path: "data/results"

# Logging configuration
logging:
  config_path: "config/logging_config.yaml"
  log_to_console: false

# Backtest configuration
backtest_config:
  initial_capital: 15000
  max_allocation_pct: 0.25
  commission_pct: 0.001  # 0.1% commission
  slippage_pct: 0.001   # 0.1% slippage
  max_positions: 5
  enable_fractional: true

# Strategy parameter ranges for optimization
strategy_params:
  breakout:
    lookback: [15, 20, 25]
    bb_std: [1.5, 2.0, 2.5]
    rsi_period: [10, 14, 20]
    volume_multiplier: [0.1, 0.15, 0.2]
    stop_loss_factor: [1.5, 2.0, 2.5]
    take_profit_factor: [2.0, 3.0, 4.0]
    rc_threshold: [0.3, 0.5, 0.7]
    max_allocation_pct: [0.15, 0.25, 0.33]
 
  mean_reversion:
    lookback: [15, 20, 25]
    std_dev_threshold: [1.5, 2.0, 2.5]
    rsi_period: [10, 14, 20]
    rsi_overbought: [70, 75, 80]
    rsi_oversold: [20, 25, 30]
    volume_threshold: [1.2, 1.5, 1.8]
    stop_loss_factor: [1.5, 2.0, 2.5]
    take_profit_factor: [2.5, 3.0, 3.5]
    zscore_threshold: [1.5, 2.0, 2.5]
    max_allocation_pct: [0.15, 0.25, 0.33]

# Test configurations
test_configs:
  # - file: "XRPUSD_5.csv"
  #   strategy: "mean_reversion"
  #   optimize: false
  #   plot: true
   
  # - file: "ADAUSD_30.csv"
  #   strategy: "mean_reversion"
  #   optimize: true
  #   plot: true
   
  - file: "ETHGBP_30.csv"
    strategy: "mean_reversion"
    optimize: false
    plot: true
