version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        filename: trading_bot.log 

loggers:
    trading_bot:
        level: INFO
        handlers: [console_handler, file_handler]
        propagate: false

root:
    level: INFO
    handlers: [console_handler, file_handler]